name: CI

on:
  push:
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run end-to-end test
        shell: pwsh
        run: ./test.ps1 -DownWhenDone
